### ISSUE TITLE
HtmlDialog callbacks are slow when converting objects

### ISSUE THREAD

**Issue by NeilBurkholder** [SketchUp/api-issue-tracker#555] opened 2020-10-16 13:57 UTC
The HtmlDialog callback methods from JavaScript are significantly slower when passing on object than when passing a string and parsing it in ruby.

See here for discussion and benchmarks. 

[https://forums.sketchup.com/t/htmldialog-callbacks/135827/6](https://forums.sketchup.com/t/htmldialog-callbacks/135827/6)

**Comment by DanRathbun** [comment] 2020-10-16 14:47
Duplicate of #554

**Comment by NeilBurkholder** [comment] 2020-10-16 14:53
I edited my original and it created a new issue!

**Closed** 2020-10-16 14:53 UTC
