### ISSUE TITLE
Loading outside components is taking a lot of time for files as big as 400MB.

### ISSUE THREAD

**Issue by Nithin-1997** [SketchUp/api-issue-tracker#808] opened 2022-07-21 10:18 UTC
# API Issues Only

*Please note that this is a tracker for the SketchUp and LayOut APIs only.*

Bugs or feature requests that do not relate to the APIs will be removed. Fill in as much details as possible.

# Bug Reports

Please include the following:

1. SketchUp/LayOut Version: All versions
2. OS Platform: Mac

Describe briefly what you are doing and what is happening.
I'm using the Sketchup.active_model.definitions.load(filepath) API to load a new component inside my working model. It's taking up as much as 30-40 seconds to load just one file.

Describe what the expected result is.
Need to find a solution to make the component loading in the definitions list faster

```ruby
# Complete reprodusible code snippet. (Important!)
```

Sketchup.active_model.definitions.load("filepath")

```c
// Complete reprodusible code snippet. (Important!)
```

Attach any relevant files.

# Feature Requests

1. Describe what you are trying to do on a high-level overview. What is your use-case?
2. If you have a spesific implementation in mind, please explain your reasoning to why it should be like that.

**Comment by thomthom** [comment] 2022-07-26 10:06
Duplicate of #807

**Closed by thomthom** 2022-07-26 10:06 UTC
