### ISSUE TITLE
SUTypedValueGetArrayItems() has unexpected behaviour

### ISSUE THREAD

**Issue by TommyKaneko** [SketchUp/api-issue-tracker#54] opened 2018-02-20 00:03 UTC
Bug on SU 2018 API, Mac and Windows

The 'array' of SUTypedValueRefs returned by SUTypedValueGetArrayItems() has unexpected behaviour.  I have noticed that releasing the first SUTypedValueRef item in the array seems to release all subsequent SUTypedValueRef objects in the array.

The issue was picked up through the SU C++ Wrapper.  This bug is especially problematic, as it prevents SUTypedValueRef objects within an array to be treated as distinct objects as one would want with C++.

More details here:
https://github.com/TommyKaneko/Sketchup-API-C-Wrapper/issues/19#issuecomment-366829846

I hope I am correct in my analysis - it took a while to figure this out.

**Comment by jimfoltz** [comment] 2018-02-20 09:12
This may or may not be related - calling `SUTypedValueGetArrayItems()` doesn't set the 4th parameter which is meant to be the number of elements returned.  The output array is populated, but the count is always 0 for me. 
[
Source example](https://github.com/jimfoltz/jf-sketchup-c-api-sandbox/blob/exp/typed-value-array-example/src/main.cpp)

**Comment by thomthom** [comment] 2018-02-20 10:55
> This may or may not be related - calling SUTypedValueGetArrayItems() doesn't set the 4th parameter which is meant to be the number of elements returned. The output array is populated, but the count is always 0 for me.

I can confirm that the source code isn't setting that count even though it populate the array. That's a bug for sure. Though that is separate from Tommy's reported issue.

**Comment by thomthom** [comment] 2018-02-20 10:56
@TommyKaneko - can you provide a minimal code example and update your original post please. It's unclear to me exactly what is being observed and done here.

**Comment by TommyKaneko** [comment] 2018-02-20 11:39
@thomthom Code example is here:
https://github.com/TommyKaneko/SU-Sandbox/blob/master/src/SUTypedValueGetArrayItems_test/main.cpp

The problem is on line 37.  The problem being that each TypedValueRef returned cannot be released independently.

**Comment by thomthom** [comment] 2018-02-20 11:54
I can reproduce - not sure what is causing it.

However, here is a version that doesn't have memory leaks:

```cpp
int _tmain(int argc, _TCHAR* argv[])
{
  std::string project_path = "C:\\Users\\tthomas2\\SourceTree\\SLAPI-Test";
  std::string model_path = project_path + "\\models\\issue-19.skp";
  std::string temp_path = project_path + "\\temp";

  SUInitialize();

  SUModelRef model = SU_INVALID;
  SU(SUModelCreateFromFile(&model, model_path.c_str()));

  SUAttributeDictionaryRef dict_ref =  SU_INVALID ;
  SUResult res = SUModelGetAttributeDictionary(model, "TypedValues", &dict_ref);
  
  SUTypedValueRef val = SU_INVALID;
  SUTypedValueCreate(&val);
  const char* key_char = "Array";
  res = SUAttributeDictionaryGetValue(dict_ref, &key_char[0], &val);
  assert(res == SU_ERROR_NONE);

  size_t count = 0;
  res = SUTypedValueGetNumArrayItems(val, &count);
  assert(res == SU_ERROR_NONE);
  std::vector<SUTypedValueRef> values(count, SU_INVALID);
  res = SUTypedValueGetArrayItems(val, values.size(), values.data(), &count);
  assert(res == SU_ERROR_NONE);

  for (auto& value : values) {
    // Do stuff with the typed Values
    SUTypedValueType type;
    res = SUTypedValueGetType(value, &type);
    std::cout << "TypedValue type is No: " << type << "\n";
    // Then release each one
    SUTypedValueRelease(&value); // CRASH on second pass - indicates TypedValue has already been released.
  }

  SU(SUModelRelease(&model));

  SUTerminate();
  return 0;
}
```

**Comment by thomthom** [comment] 2018-02-20 12:03
Looking close at this, the first `SUTypedValueRelease` doesn't have any relevance.
If you directly try to release the second item; `SUTypedValueRelease(&values[1]);` it still crashes.

Seems like only the first item from `SUTypedValueGetArrayItems` is valid.

**Comment by thomthom** [comment] 2018-02-20 12:25
@BugraBarin - is `SUTypedValue` objected returned from `SUTypedValueGetArrayItems` supposed to be released? The documentation only mentions to use `SUTypedValueRelease` after using `SUTypedValueCreate`.

Is the elements returned from `SUTypedValueGetArrayItems` owned by the containing `SUTypeRef`?

I only saw a couple of usages of `SUTypedValueGetArrayItems` and none of them released the typed values the array.

**Comment by TommyKaneko** [comment] 2018-02-20 12:30
> I only saw a couple of usages of SUTypedValueGetArrayItems and none of them released the typed values the array.
Is this acceptable behaviour in your view?  From the C++ Wrapper perspective, this becomes tricky, as some TypedValue objects need to be released on object destruction, and others in this case do not.  Would prefer consistent behaviour.

**Comment by thomthom** [comment] 2018-02-20 12:40
I've not used `SUTypedValue` myself - first time I looked at the code.

> Or perhaps we should think of an Array of TypedValue objects as being "attached" to the original TypedValue that it was extracted from?

I'm starting to wonder if this is the case - like getting a face from the model. But need to dig deeper. It isn't completely obvious to me either. This is either a bug or a documentation issue.

**Comment by thomthom** [comment] 2018-02-20 14:16
> This may or may not be related - calling SUTypedValueGetArrayItems() doesn't set the 4th parameter which is meant to be the number of elements returned. The output array is populated, but the count is always 0 for me

Logged as SU-38670

**Comment by BugraBarin** [comment] 2018-02-20 15:49
I wasn't very familiar with this function either but it looks like the typed values contained within an "array type" typed value is owned by that typed value. So the contained typed values must not be released individually. Only the container typed value need to be released. We certainly need to make this clear in the docs.

But, you could look at it this way: Since you didn't actually allocate the typed values yourself (via SUTypedValueCreate), you shouldn't release them either. You are only allocating the references there, the actual data is populated by (and owned by) the parent SUTypedValueRef (which is an "array" type).

I know this is a bit of a mind bender. Let me know if anything is unclear.

**Comment by TommyKaneko** [comment] 2018-02-20 15:51
I can understand that reasoning.  I think this should be made clear in the docs in that case.

**Comment by jimfoltz** [comment] 2018-02-20 23:14
Thanks for the code & comments, @thomthom .  Care to share your `SU` macro?

**Comment by thomthom** [comment] 2018-02-21 09:53
@jimfoltz Sure thing. It's just a different take on handling errors. I'm not so keen on automatically throwing so I assert instead:

```cpp
#include <assert.h>

#define SU(api_function_call) {\
  SUResult su_api_result = api_function_call;\
  assert(SU_ERROR_NONE == su_api_result);\
}\
```

The throwing is fine is you expect you app to crash upon failure. But if you start catching the errors to recover you'll probably leak memory at some point. (Unless you use Tommy's C++ wrapper which should ensure memory is managed - thus cleaned up in destructors .)

Additionally - I use this in combination to test the C API - in which case I some times want to continue executing the code. but have the debugger stop on the asserts.

**Comment by thomthom** [comment] 2018-02-21 09:54
Bugra have already submitted a documentation improvement to these functions. Should be available on the next SDK drop.

**Closed by thomthom** 2018-02-21 09:54 UTC
Labels: C API, SketchUp, bug
