### ISSUE TITLE
SelectionObserver won't fire if operation is open

### ISSUE THREAD

**Issue by NeilBurkholder** [SketchUp/api-issue-tracker#626] opened 2021-04-10 12:38 UTC
If a transaction is left open (usually due to an error being encountered), SelectionObserver events are queued up and don't trigger until the transaction is either aborted or commited.

Steps to reproduce:

1. Enter the following code snippet:

```ruby
module Test_Bug
  extend self

  class SelObserver < Sketchup::SelectionObserver
    def onSelectionBulkChange(selection)
      puts "BulkChange #{selection.count} items"
    end

    def onSelectionCleared(_selection)
      puts "onSelectionCleared"
    end
  end

  @ob = SelObserver.new
  Sketchup.active_model.selection.add_observer(@ob)

  def unthaw
    Sketchup.active_model.abort_operation
  end

  def freeze_up
    Sketchup.active_model.start_operation('Test Transaction', true)
    #cause error
    Sketchup.active_model.entities.add_face([0, 0, 0])
    Sketchup.active_model.commit_operation
  end

  def freeze_up2
    Sketchup.active_model.start_operation('Test Transaction')
    #cause error
    Sketchup.active_model.entities.add_face([0, 0, 0])
    Sketchup.active_model.commit_operation
  end
end
```

2. call the freeze_up method enter an open transaction.
3. Make several selection changes to the model, and not that the events are not triggered.
4. call the unthaw method, and note that all the queued events are called.

Expected results: Events should be triggered as they occur. I this is by design then it should be documented in the api docs.

**Comment by thomthom** [comment] 2021-04-12 08:46
Since SU2016 any observer won't trigger while an operation is open. This is by design. Allowing observers to trigger in the middle of operations was a major source of crashes and instability.

It has the unfortunate side-effect in the case of errors occurring that until the operation is closed (which happen automatically upon a new operation) no observers are triggered. This is however considered an edge case and a bug in the usage of the API.

We should however improve the documentation examples for this though, showing a could of ways to handle this:

```
module Example

  def self.abort_on_error
    model.start_operation('Abandon ship!', true)
    # Might raise error....
    model.commit_operation
  rescue
    model.abort_operation
    raise # reraise it so it can be captured by the caller to handle messages to the user
  end

  def self.commit_on_error
    model.start_operation('Keep what we got', true)
    # Might raise error....
  ensure
    model.commit_operation
  end

end
```

Note that I'm using the whole method as a block to rescue in. You might handle it more locally by using `begin` + `end`

```
module Example

  def self.locally_handling_errors
    # setup code here that we don't want to respond to with abort_operation if we raise
    begin # Narrow the scope for capturing errors around the operation.
      model.start_operation('Abandon ship!', true)
      # Might raise error....
      model.commit_operation
    rescue
      model.abort_operation
      raise # reraise it so it can be captured by the caller to handle messages to the user
    end
  end

end
```

You could also make yourself helper methods for this:

```
module Example

  # For normal operations.
  def self.operation(model, name, &block)
    model.start_operation(name, true)
    block.call
    model.commit_operation
  rescue
    model.abort_operation
    raise
  end

  # For operations within observers, chaining to the operation it reacts to.
  def self.append_operation(model, &block)
    model.start_operation('[no-name]', true, false, true)
    block.call
    model.commit_operation
  rescue
    # Note that we don't abort a transparent operation. This is because it
    # would abort the operation it chains to. In this case it's probably best to just
    # commit and move on.
    model.commit_operation
    raise
  end

end
```

**Comment by thomthom** [comment] 2021-04-12 08:48
Closing as Working as Intended.

**Closed by thomthom** 2021-04-12 08:48 UTC
Labels: Ruby API, SketchUp, observer, working as intended

**Comment by NeilBurkholder** [comment] 2021-04-12 09:17
Thanks for the clarification.

**Comment by thomthom** [comment] 2021-04-12 10:51
hm... maybe I should convert this to a documentation issue....

**Comment by NeilBurkholder** [comment] 2021-04-12 10:58
> hm... maybe I should convert this to a documentation issue....

> Expected results: Events should be triggered as they occur. **If this is by design then it should be documented in the api docs.**

A little clarification in the docs might save someone some debugging time in the future.
