### ISSUE TITLE
Class: Sketchup::Text is any api can change text‘s’letter_height 

### ISSUE THREAD

**Issue by asis991** [SketchUp/api-issue-tracker#887] opened 2023-03-29 06:15 UTC
Is any api can change text‘s’letter_height ,when i see Sketchup::Text api has no suitable method to change text's size .like change text's size through Element information ,thanks

![1](https://user-images.githubusercontent.com/124273813/228442374-a9a7c2bd-762b-4f20-96a3-803fc39489d9.png)

![2](https://user-images.githubusercontent.com/124273813/228442418-c2bd0c48-fd51-4261-8ee2-a04e20e8b9f8.png)

**Comment by DanRathbun** [comment] 2023-03-29 19:35
**Duplicate of:**

* [Issue 47 : Text Labels Properties, Font and Attachment](https://github.com/SketchUp/api-issue-tracker/issues/47) - SU-40230 (9 AUG 2018)
... and ...
* [Issue 782 : Minimal enhancement to create dimensions and texts using ruby](https://github.com/SketchUp/api-issue-tracker/issues/782) - SKEXT-3513 (9 SEP 2022)

But also requested in public forums in NOV 2015 ...
https://forums.sketchup.com/t/set-font-characteristics-for-leader-text-or-dimension-text/17689
http://forums.sketchup.com/t/dimension-font-and-height-cant-be-changed/7375
... in which I and other coders noted that we've asked for this feature 7 years before then.

**So this feature request dates back to ~2008 !**

----

## REFERENCE RELATED

### Previous Issues
#### Ruby API
* [Issue 47 : Text Labels Properties, Font and Attachment](https://github.com/SketchUp/api-issue-tracker/issues/47)
* [Issue 48 : Dimensions Properties, Font and Attachment](https://github.com/SketchUp/api-issue-tracker/issues/48)
* [Issue 224 : Need "DimensionsOptions" Sketchup::OptionsProvider instance](https://github.com/SketchUp/api-issue-tracker/issues/224)
#### C API
* [Issue 434 : SUFontCreate() and SUModelAddFont()](https://github.com/SketchUp/api-issue-tracker/issues/434)

----
### Forum Topics
#### Ruby API
* [Set font characteristics for leader text or dimension text](https://forums.sketchup.com/t/set-font-characteristics-for-leader-text-or-dimension-text/17689)
#### C API
* [SUFontCreate functionality missing](https://forums.sketchup.com/t/sufontcreate-functionality-missing/116770)
* [Copy SUTextRef Error](https://forums.sketchup.com/t/copy-sutextref-error/173717)

~

**Comment by asis991** [comment] 2023-03-30 03:17
> **Duplicate of:**
> 
> * [Issue 47 : Text Labels Properties, Font and Attachment](https://github.com/SketchUp/api-issue-tracker/issues/47) - SU-40230 (9 AUG 2018)
>   ... and ...
> * [Issue 782 : Minimal enhancement to create dimensions and texts using ruby](https://github.com/SketchUp/api-issue-tracker/issues/782) - SKEXT-3513 (9 SEP 2022)
> 
> But also requested in public forums in NOV 2015 ... https://forums.sketchup.com/t/set-font-characteristics-for-leader-text-or-dimension-text/17689 http://forums.sketchup.com/t/dimension-font-and-height-cant-be-changed/7375 ... in which I and other coders noted that we've asked for this feature 7 years before then.
> 
> **So this feature request dates back to ~2008 !**
> 
> ## REFERENCE RELATED
> ### Previous Issues
> #### Ruby API
> * [Issue 47 : Text Labels Properties, Font and Attachment](https://github.com/SketchUp/api-issue-tracker/issues/47)
> * [Issue 48 : Dimensions Properties, Font and Attachment](https://github.com/SketchUp/api-issue-tracker/issues/48)
> * [Issue 224 : Need "DimensionsOptions" Sketchup::OptionsProvider instance](https://github.com/SketchUp/api-issue-tracker/issues/224)
> 
> #### C API
> * [Issue 434 : SUFontCreate() and SUModelAddFont()](https://github.com/SketchUp/api-issue-tracker/issues/434)
> 
> ### Forum Topics
> #### Ruby API
> * [Set font characteristics for leader text or dimension text](https://forums.sketchup.com/t/set-font-characteristics-for-leader-text-or-dimension-text/17689)
> 
> #### C API
> * [SUFontCreate functionality missing](https://forums.sketchup.com/t/sufontcreate-functionality-missing/116770)
> * [Copy SUTextRef Error](https://forums.sketchup.com/t/copy-sutextref-error/173717)
> 
> ~

thanks  for your answer

**Closed** 2023-03-30 03:18 UTC
Labels: enhancement, Ruby API, SketchUp, parity

**Comment by DanRathbun** [comment] 2023-03-30 13:11
No problem. (But you need not parrot the entirety of previous posts.)
