### ISSUE TITLE
SUModelGetScenes returns SU_ERROR_GENERIC

### ISSUE THREAD

**Issue by tommash** [SketchUp/api-issue-tracker#301] opened 2019-07-30 09:38 UTC
1. SketchUp 19.2 initial release
2. OS Platform: Win

Cannot get a list of scenes from a live model.
Count of scenes returns correct number, but the call to SUModelGetScenes() reutrns SU_ERROR_GENERIC

> 		size_t count = 0;
> 		SUModelGetNumScenes(mod, &count);
> 
> 		if (count != 0)
> 		{
> 			std::vector<SUSceneRef> scenes(count);
> 			SUResult sr = SUModelGetScenes(mod, count, &scenes[0], &count);
> 
> 			if ( sr == SU_ERROR_NONE)
> 			{
> 
> 			}
> 		}

**Comment by thomthom** [comment] 2019-07-30 11:56
I'm unable to reproduce this.

![image](https://user-images.githubusercontent.com/192418/62127009-52e29200-b2d1-11e9-83e7-37f4b4a0d6a7.png)

https://github.com/thomthom/ruby-c-extension-examples/blob/1118f86885a6da58cf8b5e602d53de27ed09c084/Hello%20World/src/SUEX_HelloWorld.cpp#L152-L170

Are you linking against `sketchup.lib`? If you link against `SketchUpAPI.lib` the C API won't work propertly.

More details here: https://forums.sketchup.com/t/best-practice-to-support-multiple-sketchup-versions/96018/15?u=tt_su

**Comment by tommash** [comment] 2019-07-30 12:58
I linked indeed against SketchUpAPI.lib.
When I link against sketchup.lib from SU2019.2 SDK I get 4 unresolved symbols...
SUMaterialGetColorizeType
SUTextureWriteOriginalToFile
SUModelGetNumImageDefinitions
SUModelGetImageDefinitions

**Comment by tommash** [comment] 2019-07-30 13:35
I confirm that linking against sketchup.lib fixed the SU_ERROR_GENERIC issue and probably a lot more, but how I definitely need those 4 functions.

**Comment by DanRathbun** [comment] 2019-07-30 19:12
The SDK has differing version numbers than the application, so we'd hope that the SDK could be fixed independently.

**Comment by thomthom** [comment] 2019-07-31 10:13
Yea, it looks like we need to rebuild the sketchup.lib as it hasn't fully exported all the symbols. I think we should be able to do so without needing a new client build.

And you're right, we need better documentation for setting up the Live C API.

**Comment by thomthom** [comment] 2019-07-31 11:36
We think we have a fixed `sketchup.lib` now. We'll just need to run some extra verification steps before we push an updated SDK package.

**Comment by thomthom** [comment] 2019-07-31 11:39
> The SDK has differing version numbers than the application, so we'd hope that the SDK could be fixed independently. 

If it's been for the standalone SDK binaries then yet it'd certainly be the case. But with the Live C API we was afraid the functions was also missing from SketchUp.exe - in which case a new SketchUp release would have to be made.

Fortunately it was just the symbols in `sketchup.lib` - so we should be good.

**Closed** 2019-08-20 13:18 UTC
Labels: C API, Live C API, SketchUp, bug, invalid
