### ISSUE TITLE
Pages#add allows non-unique name

### ISSUE THREAD

**Issue by Eneroth3** [SketchUp/api-issue-tracker#397] opened 2019-12-07 14:16 UTC
In SketchUp scenes names are not supposed to be duplicated. If you try it from the UI you get an error message and from the API you can use the name as an identifier to look up the Page object.

Yet you can create numerous scenes by the same name from the API.

```ruby
Sketchup.active_model.pages.add("Lol")
Sketchup.active_model.pages.add("Lol")
Sketchup.active_model.pages.add("Lol")
```

I propose automatically adding a counter on the name, i.e. "Lol", "lol 1", "Lol 2". This is convenient for API users, and from what can see shouldn't create more issues with any existing code than raising an exception would.

**Comment by jinyistyle** [comment] 2020-01-21 21:47
SU-45221

**Comment by thomthom** [comment] 2020-03-26 12:49
Duplicate of #261

**Closed by thomthom** 2020-03-26 12:49 UTC
Labels: Ruby API, SketchUp, bug, logged
