### ISSUE TITLE
Request for direct access to placed entities in #place_component method

### ISSUE THREAD

**Issue by indie3d** [SketchUp/api-issue-tracker#860] opened 2023-01-15 09:26 UTC
Why does the #place_component method in the SketchUp API return the SketchUp::Model instead of the entities placed as an array?

In my opinion, returning the placed entities in an array would make it easier to perform actions on them, saving time and increasing efficiency by not having to search for them using less optimal ways.

**Comment by Eneroth3** [comment] 2023-01-15 10:27
The return happens instantly when you call the method, so it doesn’t yet know of what entities will be placed when you later click in the model. However, the method could perhaps yield the placed entity to an optional code block each time you place something. I think I have manually recreated this with observers in one of my projects, but I think it would be beneficial to have it in the api directly.

**Comment by DanRathbun** [comment] 2023-01-15 15:16
This has already (2017) been discussed and proposed in [Issue #6: **Model#load_and_place_component**](https://github.com/SketchUp/api-issue-tracker/issues/6).

----

_Please use the search feature before opening new issues. Otherwise we get competing discussion threads._

_Perhaps relabel this as a question and close it?_

**Comment by thomthom** [comment] 2023-01-16 09:15
Closing as duplicate of #6

**Closed by thomthom** 2023-01-16 09:15 UTC
Labels: duplicate, enhancement, Ruby API, SketchUp
