### ISSUE TITLE
HtmlDialog being closed by Ruby garbage collection

### ISSUE THREAD

**Issue by Eneroth3** [SketchUp/api-issue-tracker#60] opened 2018-03-06 18:05 UTC
If a HtmlDialog doesn't have a Ruby reference the dialog disappears when the Ruby garbage collection runs. In most cases this isn't a problem, as the variable pointing to the dialog usually is referenced somewhere in the code, e.g. from the block used as callback.

However, if there is no callback and no other persistent reference to the dialog it can magically disappear.

It is quite easy for a extension developer to make sure there is a persistent reference to the dialog, but without knowing you have to make one it is very hard to figure out why the dialog suddenly disappears without any user interaction.

````ruby
def method
  dlg = UI::HtmlDialog.new(dialog_title: "About My Awesome Extension")
  dlg.set_html("Version: 1.0.0<br />Author: Ms Awesome")
  dlg.show
  # dlg has no callbacks as it simply shows static information.
  # dlg is no longer referenced when method is finished.
end

method

# Dialog disappears by itself after some minute, or when manually calling GC.start.
GC.start
````

I suggest, if possible, the dialog stays open even if the variable pointing at it is garbage collected.

Confirmed on SU17 an 18 on Win7.

Forum thread: https://forums.sketchup.com/t/htmldialog-closing-by-itself/63280

**Comment by DanRathbun** [comment] 2018-03-06 20:48
> I suggest, if possible, the dialog stays open even if the variable pointing at it is garbage collected.

I don't think this is a good idea. Redesigning Ruby GC is way beyond what any API should do.

The OP solved his "apparent issue" when told to use a persistent reference to the dialog object, instead of a local reference that went out of scope when the method returned.
https://forums.sketchup.com/t/htmldialog-closing-by-itself/63280/

The API should encourage good coding practice.

That said, there is a simple way to have SketchUp itself hold dialog references, and that is a dialog collection that each dialog class keeps of all it's instances. (Similar to a toolstack.)

**Comment by Eneroth3** [comment] 2018-03-06 21:04
I think you miss the point. Just that the OP of this specific SketchUp thread got it to work by fixing some other code issue doesn't mean this isn't an API bug. There are other use cases when there is no reason to hold a reference to the dialog object in Ruby, as I have shown in the code example.

I do not in any way suggest the Ruby API should change how Ruby handles the garbage collection. What I suggest is for the dialog to stay open, regardless of whether there is a Ruby variable pointing at it or not.

**Comment by DanRathbun** [comment] 2018-03-06 23:29
> I think you miss the point.

From my point of view, the **real point** is, it is **not** a bug. 
It is **expected** behavior in object oriented programming. 

I am opposing to this request at a **fundamental** level.

IMO the API programmers would _likely_ never set a precedent for any API by doing this. (Ie, it opens "Pandora's box" resulting in more demands that the API implement similar features throughout the API.)

And so, **I have exercised my right to down vote this request.**

**Comment by Eneroth3** [comment] 2018-03-07 07:12
You definitely miss the point!

We are not even talking about the Ruby object oriented world here! The variable should be garbage collected and destroyed, just as it is. But that doesn't mean the Chromium window has to close.

If this is hard to fix for technical reasons there should at least be a big warning, and a code example explaning the warning, in the documentation.

**Comment by thomthom** [comment] 2018-03-07 11:53
This is the same behaviour `UI::WebDialog` exhibit. Ruby owns that dialog and the memory allocation to it.

This is something that can be alleviated by expanding on the documentation.

**Comment by Eneroth3** [comment] 2018-03-07 20:55
Here's the simplest code I've managed to produce to work around this behavior. However ideally I don't think a Ruby developer should have to think about garbage collection, and not have to resort use dummy references to override garbage collection to affect something seemingly outside of the Ruby environment. If possible I think it would be beneficial to include this, or another, workaround under the hood in Sketchup and have the API "just work".

````ruby
def show_static_info
  dlg = UI::HtmlDialog.new(dialog_title: "About Some Extension")
  dlg.set_html("Version: 1.0.0")
  dlg.show

  # Hack: The Chromium window is closed when its Ruby object is recycled by the
  # Ruby garbage collector.
  # To prevent the window from closing seemingly randomly when the GC runs,
  # make an arbitrary reference to it in a callback.
  # To allow the object to be recycled once the dialog closes, set the variable
  # to nil.
  dlg.set_on_closed { dlg = nil }
end
````

Here's the full code I've used to test that the hack above works. The code is intended to be executed one paragraph at a time to check the return values in between.

````ruby
require 'weakref'
def show_static_info
  dlg = UI::HtmlDialog.new(dialog_title: "About Some Extension")
  dlg.set_html("Version: 1.0.0")
  dlg.show

  # Hack: The Chromium window is closed when its Ruby object is recycled by the
  # Ruby garbage collector.
  # To prevent the window from closing seemingly randomly when the GC runs,
  # make an arbitrary reference to it in a callback.
  # To allow the object to be recycled once the dialog closes, set the variable
  # to nil.
  dlg.set_on_closed { dlg = nil }
  
  # Return the object so we can create a weakRef for testing purpose.
  # Assume no hard reference is kept.
  # In a real life situation this method would return nil.
  dlg
end
wr =  WeakRef.new(show_static_info)
wr.weakref_alive?
# => true

GC.start
wr.weakref_alive?
# => true

# Manually close the dialog here by pressing the close button.

GC.start
wr.weakref_alive?
# => nil
````

**Comment by MSP-Greg** [comment] 2018-03-07 21:29
Objects don't exist without a reference.  This isn't about GC or anything else.  It's also a common concept with many programming languages.

Isn't this as simple as (could be a module or a class):

```ruby
# frozen_string_literal: true
# load <path to file> ; StayingAlive.show_dlg
module StayingAlive
  def self.show_dlg
    @@dlg = UI::HtmlDialog.new dialog_title: "Staying Alive"

    @@dlg.set_html  <<-HTML
    <html><body>
      Use a class variable or anything that stays alive...
    </body></html>
    HTML

    @@dlg.show
    @@dlg.set_on_closed { @@dlg = nil }
  end
end
```

**Comment by MSP-Greg** [comment] 2018-03-08 04:27
@Eneroth3

One thing to consider when thinking about the SU API is that it is very 'factory' oriented.  Generally, there are two concepts behind object creation.

The first is the constructor/initializer, where (in Ruby) a `.new` method is used.  The other is the factory concept, where a method, often associated with a collection, is called with enough information to create an object.  Factory methods usually return the newly created object, but the object is also often added to the collection.

As a comparison, compare the number of 'add' methods vs 'new' methods in the [SketchUP API](https://msp-greg.github.io/su/) vs the number of 'new' methods in the [Rails API](https://msp-greg.github.io/rails_master/) (click on methods top left, then search with a capital first letter, which does a 'start of name' search, or to really burrow down, type 'Sketchup.New', and for more fun, compare that to 'Sketchup.new').  FYI, Rails has about 11_000 methods...

Anyway, my point is that one shouldn't expect similar behavior when comparing factory created objects and constructor/initializer created objects.  After all, if one creates an array in one method and wants to use it in other methods (or other classes/modules), it needs persistence to do so.  Otherwise, after the method it was created in ends, so does the array.  Funny how both arrays and dialogs are both constructor/initializer objects...

Greg

**Comment by thomthom** [comment] 2018-03-08 10:21
As Greg mentions, you only need an instance variable (or class variable) inside a module to hold on to the dialog.

One of the drawbacks with garbage collection languages like Ruby is that object ownership if often muddled up. If a developer only ever used a GC based language they tend to rely on the "magic" of GC to clean up.

Combine that with the factory methods for entities in the SketchUp, extensions developers are further detached from the notion of object ownership.

The behaviour of the dialogs are as expected. But we'll update the documentation to clarify the ownership rules.

**Comment by DanRathbun** [comment] 2018-03-08 10:34
> @Eneroth3 You definitely miss the point!

( _Note - Changed from the second to the third person POV_. )

**Disagreeing with points made by others, is not missing them, nor is coming to differing conclusions.** 
Not everyone will agree with every idea. And she has disagreed with many of my ideas. It happens.

Also, I like the way it is now, because it affords the opportunity to teach about the persistence of Ruby objects and the differences between the various types of references. **And it is expected behavior for Ruby and it's garbage collection.** In addition, there are other more important API features that I prefer to support.

I and others have not disagreed with this feature request out of spite or in an offhand manner. Instead at least 3 experienced people have given their reasons why they oppose the idea, or tried to educate (here and in the public thread,) on garbage collection and persistence of objects, or why they dislike this request based upon fundamental OOP precepts.

But in return, she has decided to remain defiantly obstinate, make repeated ad hominem barbs that border on disrespectful and insulting. (**ADD**: Her last public forum post on this is absolutely **slanderous**.)
The repeated barb [quoted above] is why she earned a "thumbs down" for that post from me, not for anything else in that post, [which was just opinion.] The "down vote" on the FR in general is on the OP, and follows Thomas' instructions for voting on SketchUp API Featue Requests.
But, I see that in retaliation, all my posts in this thread have been churlishly marked with a "thumbs down".

I believe this feature request is misinformed, evidenced by repeated false or twisted statements about the nature of garbage collection and OOP in general. (I also posted weblinks to GC info in the [public forum thread](https://forums.sketchup.com/t/htmldialog-closing-by-itself/63280/30?u=danrathbun) for anyone wanting to know more how garbage collection works.)

Because I feel incorrect statements of fact to support a Feature Request, should not remain unchallenged, I'll just point out a few more of the invalid statements, ... maybe other readers (who are interested) will learn something. 
(Note, FYI, in the public forum thread JCE has posted one last insulting rant, blaming everyone else who disagreed with not understanding, slandered me and then muted the thread. She stated she's not interest in "technical excuses", so everything here is likely to fall on "deaf ears".)

> @Eneroth3 The variable should be garbage collected and destroyed, just as it is. 

This is another incorrect statement indicating the need to become better informed about how garbage collection works.

(Just for clarity as to what I say below ...,) in Ruby, the word "variable" means a reference identifier that points at an object. (It can have another specific meaning and use in other non-OOP coding languages.)

**Garbage collection does _not_ collect or destroy references** (_aka_ variables.) Garbage collection frees **memory** allocated to objects that are **no longer in use**. The primary way that garbage collection can know whether such memory allocations are "in use" is whether they are referenced or not. ( [Websearch on "Mark and Sweep"](https://www.google.com/search?q=mark+and+sweep+garbage+collection) )

> @Eneroth3 I don't think a Ruby developer should have to think about garbage collection, ...

On the contrary, the concept of garbage collection is one of the intermediate features that Ruby programmers should learn when they move on to more advanced understanding of Ruby programming.

In the SketchUp realm, we are operating within a shared environment and saving memory should be a concern at some point, especially when a coder develops larger and more memory intensive extensions.
On the MS Windows platform each application process has a limited amount of memory usage allowed.

> @Eneroth3 ... and not have to resort use dummy references to override garbage collection ...

This statement is the opposite of reality. GC only reclaims memory from unused unreferenced objects.
References are never "dummy", they are required for the persistence of objects beyond the local scope. Using references to prevent their referenced objects from being destroyed is normal OOP coding. **It is not anything out of ordinary.** Styling it as "to override garbage collection" is just a weird contrary twist on GC and OOP.

> @Eneroth3 ... to affect something seemingly outside of the Ruby environment. 

Currently, the implementation is that they (the Ruby dialog object, the CEF instance and the platform framework window object) are linked, by design. This is not surprising in any way. It is totally expected that objects in OOP environments will be referenced so those objects can be controlled.

**Okay, so there has been found a minority case in which no further control over the dialog, it's window or the content is desired.** I'd guess this wasn't thought of when the `UI::HtmlDialog` interface was designed, but this does not mean the class is bugged. **Also, this does not mean that the linkage or dependence upon the Ruby reference should be disconnected in ALL instances**.

> @Eneroth3 But that doesn't mean the Chromium window has to close.

Well **it does if the interface is designed this way**. If the window object's "owner", which is the Ruby dialog object becomes unreferenced and is garbage collected, then the CEF or it's internal SketchUp API C interface, properly interprets this as time to deallocate the platform window object and the CEF instance and destroy them. **This appears to be the way that the API's internal interface to CEF and it's window is currently designed.**

Think about it a minute. If we dereference any object we are effectively telling Ruby and therefore SketchUp's API that we are done using this object. Ruby doesn't care (and probably cannot see) how the object became unreferenced. Ie, whether it was deliberately set to point at **`nil`**, or whether the reference itself went out of scope and ceased to exist. Either way, the object itself no longer has any references pointing at it, and is now eligible for GC.

Implementing this request for **ALL** html dialogs will complicate dialog coding, and cause code breakage, so it'd need to be done **ONLY** for those minority situations where you want SketchUp to hold the reference internally instead of your code. (See below in optional ideas section.)

In most cases SketchUp Ruby extension developers **do not** want their Ruby dialog objects automatically GC'd when it's window is closed. **So this cannot be a feature that is applied to ALL html dialogs.** It would break code "in the wild" and upset coders who expect to have control over persistence of their OOP dialog objects.

**So, such implementation must be optional, ... IF it is implemented.**

----
### Optional Implementation Ideas

Obviously there is a C++ window closure event happening that in turn must call any Ruby-side closure block when one has been defined. This could be leveraged for an optional unreferenced scenario. 

The trick is to not cause havoc, as the is an intricate dance going on between an embedded Ruby subprocess, SketchUp API C interface, SketchUp's internal C++ engine, the Chrome Extension Framework, and Microsoft Foundation Class objects (or whatever framework objects are in use on the Mac.)

The only alternatives to the `dlg#set_on_closed { dlg=nil }` block (suggested and shown by both Steve and Greg,) would be a **constructor** options hash property called say, `"persist_until_closed: true"` ... 
or ... a similarly named instance method, ...
or ... a new style type constant, say ... **`UI::HtmlDialog::STYLE_DESTROY_ON_CLOSE`**

... that just simply does the same thing (as Steve and Greg have shown) transparently "under the bonnet".
The class constructor would then know that the reference would be created and kept on the C-side until the platform window is closed.

In the case of the style constant, it would bitwise ORed with whatever other style constant is desired. (Ie, it'd be a behavior modifier.)
```ruby
UI::HtmlDialog::new(
  dialog_title: "Whoops!",
  style: UI::HtmlDialog::STYLE_DIALOG | UI::HtmlDialog::STYLE_DESTROY_ON_CLOSE,
  # ... other properties ...
).instance_eval {
  set_html("<HTML><BODY>Unknown input!</BODY></HTML>")
  show_modal
}
```
Note how I purposely avoided creating a reference there ? ;)

**Comment by DanRathbun** [comment] 2018-03-08 10:40
### Optional Implementation Ideas

Obviously there is a C++ window closure event happening that in turn must call any Ruby-side closure block when one has been defined. This could be leveraged for an optional unreferenced scenario. 

The trick is to not cause havoc, as the is an intricate dance going on between an embedded Ruby subprocess, SketchUp API C interface, SketchUp's internal C++ engine, the Chrome Extension Framework, and Microsoft Foundation Class objects (or whatever framework objects are in use on the Mac.)

The only alternatives to the `dlg#set_on_closed { dlg=nil }` block (suggested and shown by both Steve and Greg,) would be a **constructor** options hash property called say, `"persist_until_closed: true"` ... 
or ... a similarly named instance method, ...
or ... a new style type constant, say ... **`UI::HtmlDialog::STYLE_DESTROY_ON_CLOSE`**

... that just simply does the same thing (as Steve and Greg have shown) transparently "under the bonnet".
The class constructor would then know that the reference would be created and kept on the C-side until the platform window is closed.

In the case of the style constant, it would bitwise ORed with whatever other style constant is desired. (Ie, it'd be a behavior modifier.)
```ruby
UI::HtmlDialog::new(
  dialog_title: "Whoops!",
  style: UI::HtmlDialog::STYLE_DIALOG | UI::HtmlDialog::STYLE_DESTROY_ON_CLOSE,
  # ... other properties ...
).instance_eval {
  set_html("<HTML><BODY>Unknown input!</BODY></HTML>")
  show_modal
}
```
Note how I purposely avoided creating a reference there ? ;)

**Comment by MSP-Greg** [comment] 2018-03-08 16:22
Garbage collection is not really part of this issue.  The only thing it affects is the time delay before the dialog disappears.

In almost all languages, variables declared in functions/methods/procedures (FMP's) are local, and out of scope (invalid) outside of the FMP.  Where it becomes more of an issue is when variables are in some way made global or passed around to other FMP's.  Additionally, there is the issue of circular references.

Since many programs may have a great number of FMP calls when running, 'garbage collection' was set up to free 'out of scope' objects (clean memory) only when needed or at a time determined to be optimal.  Whatever is out of scope is still unavailable, but the objects may still be held in memory.  Ruby does have tools to determine what these objects are.

I've mentioned the factory methods used with many API objects, and another characteristic with these objects is that they can be created/modified/deleted by the user.  Most of the API objects that have constructors/initializers cannot be created by the user, and (as Thomas mentioned) are not part of any of the model's collections.

So, if this issue is about whether dialogs should be managed by SU, I would still vote no.  Given the examples cited (I looked at the forum thread finally), by not having a reference to the dialog, it would seem that the user could open several, as the desired code would have no means to determine whether the dialog is open.  I consider that to be bad UI design.

Dialog state must be managed in code, and that may require persistent references.

Greg

**Comment by DanRathbun** [comment] 2018-03-09 14:47
> @MSP-Greg Given the examples cited (I looked at the forum thread finally), by not having a reference to the dialog, it would seem that the user could open several, as the desired code would have no means to determine whether the dialog is open. I consider that to be bad UI design. 
Dialog state must be managed in code, and that may require persistent references.

**Agree**, this is (as you describe) would be poor dialog implementation by the extension coder.
The multiple unwanted "clone" dialog scenario has always been a coding challenge that SketchUp API coders run into early in their learning. It is another teaching / learning milestone that affords the coder to learn about the use of persistent reference to control behavior and limit instances to a singleton pattern.

So (as you point out,) without the persistent dialog reference there is no way to test if the dialog exists and is visible. (I always have a conditional that checks a module `@@dialog` reference before creating an API dialog object. If it exists and is open, I just bring to top; if it exists but is not shown, I show it; otherwise create a new object. (It's a simple, safe coding pattern that we've long promoted in all the SketchUp online coding forums that there have ever been. I myself remember posting examples of this dialog control code.)

And I just scanned through Thomas' dialog examples he has posted to the SketchUp repo archive here from DevCamp 2017 ... and steps 2 and 3 are about dialog creation and visibility control ... good patterns for coders to emulate.

https://github.com/SketchUp/htmldialog-examples

> @MSP-Greg Garbage collection is not really part of this issue. The only thing it affects is the time delay before the dialog disappears.

At first read I didn't follow your statement. So I started to think out loud, a bit ...

It seems that John Boundy's tests on the Mac show that when Ruby GC removes the unreferenced dialog object from it's memory (the Ruby stack?,) that this _somehow_ triggers a cleanup in SketchUp's C++ code, which destroys the CEF process and (Cocoa) window objects.
Same for the Windows platform except the window is a MFC window class object, and ... POOF ... the unreferenced dialog window is gone.

Re, the delay seen on Mac vs Windows, ... there is an obvious difference in how Ruby GC is operating between the two platforms, but why is **NOT** the real question of **THIS** issue, it is just something noticed when testing to reproduce the reported undesired behavior.

So this thinking got me to **agree**, if you mean that **GC isn't the root cause of the behavior**, ... ie, it is just an actor, acting (for the most part as expected and designed) in the events that result in the reported unwanted behavior of a dialog's window unexpectedly disappearing.

**Comment by DanRathbun** [comment] 2018-03-09 14:47
----

**Comment by MSP-Greg** [comment] 2018-03-09 15:27
Dan,

> if you mean that GC isn't the root cause of the behavior

Yes, and maybe stating it more clearly than earlier, the root cause is that the variable (holding the reference to the dialog) is out of scope, GC is only the cause of the timing delay in the dialog disappearance.

In general, with issues similar to this, I'm a little sensitive to API additions/changes that one might say 'fly in the face of' standard programming issues/practices.  In the Ruby core list, from time to time,  people come in with "this is really helpful/cool in Rails, can't we add it to Ruby?" requests.

The vast majority of the requests are shut down with a simple "if you want it, add it to your own code".

Likewise, given that resources always have limits, there are so many things that are 'non optimal' re Ruby & SketchUp, I wish there was more concentration on that, and not issues that are easily coded around...

<rant off> Greg

**Comment by Eneroth3** [comment] 2018-03-10 14:03
I filed this bug report much to have it documented where bugs are listed, and where API users can find it and find how to work around it. I made this bug report to contribute to the community and help, mostly new, plugin developers.

I also suggested a possible solution to what appeared to be the underlying problem  but understand rewriting the back end code for this use case likely isn't going to happen. That is why I specifically said documenting this rather unexpected behavior works too!

I didn't expect simply logging this odd behavior, for plugin developers to find, would cause a flame war whether the behavior is expected or not (hint: from an API UX perspective it is not). Thomas already marked this as needing more documentation so I don't know why some people are still arguing against the bug report.

Truth is the current behavior cannot be explained without mentioning garbage collection (because the inconsistent delay is caused by Ruby GC) or the implementation beyond the API. Yes, the current behavior makes sense from a backend engineering point of view, but not from an API UX point of view. Those saying the behavior is expected, seeing it exklusivevly from the former point of view, is missing the point I have been trying to make.

I am a firm believer the API should be as welcoming to new developers as possible, including those with little programming background. You shouldn't need a college degree in computer science, or 30 years of experience in C++, to use a Ruby API.
___

To go back to implementation details:

I'm against having two separate dialog behaviors, one destroting the dialog when closed and one closing the dialog when unreferenced (and GC has kicked in). Explaining the difference to the API user, and which one is prefererad when, is just as difficult as explaining the workaround/hack of retaining a variable you never use, just to keep the object referenced. Also Dan makes a good point about what would happen with callbacks if the Ruby object recycled but the dialog persists.

> I note this because if SketchUp silently kept dialog references to prevent GCing, (and unwanted window closure) how would SketchUp know when to release the references ?

What if SketchUp silently hold a reference to the dialog object that is separate from the reference exposed to the API user? SketchUp releases its reference when the dialog closes (and makes a new one if the dialog is re-opened) and the API user can release their reference anytime, without affecting the other reference. The object wouldn't be garbage collected, and the window not closed, until both references are released. When both the window is closed and there is no reference made by the API user, the object can be recycled to eliminate memory leaks.

**Comment by MSP-Greg** [comment] 2018-03-10 15:03
@Eneroth3

I certainly wouldn't consider this a flame war.

> whether the behavior is expected or not (hint: from an API UX perspective it is not

I don't think anyone is in disagreement about that.  We disagree as to the fix.

Re your last paragraph, I still see the 'API UX' issue of the user being able to open multiple dialogs unless the code is actually keeping track of dialog state.  To do so it needs to maintain a persistent variable.  Doing that allows the issue to go away.  No changes needed.

Some people involved in SU plugin development may have started programming with SU.  I started with Ruby from writing code for SU 7/8, but I started coding decades ago (started at a large Univ as CompSCI major), and have coded in many languages.  I started coding before 'the Internet', and I've seen the start of OOP, XML, WebSocket, etc.  Lately I've been somewhat active in the Ruby community.

Hence, I'd prefer that, rather than the API doing odd things that would be unexpected by one with a more traditional coding background, that (as you've mentioned) this issue of variable scope with dialogs be made very clear in the documentation.

>  I made this bug report to contribute to the community and help, mostly new, plugin developers.

And I appreciate anyone doing so.  Thank you.

**Comment by Eneroth3** [comment] 2018-03-10 18:16
@MSP-Greg 

Thanks for the appreciation.

> Re your last paragraph, I still see the 'API UX' issue of the user being able to open multiple dialogs unless the code is actually keeping track of dialog state.

I was about to address your previous comment on this in my last response but it got too long and maybe a bit off topic. I would refer to this as end user experience, or just UX, not API user experience. Of course it's best if the plugin developer (= API user) creates a persistent dialog that can be shown (or brought to front) if the command is reactivated. I'd also recommend adding a Close/OK button at the dialog bottom, and a javascript eventListener to close it by pressing ESC.

However this is not something you would likely do very early when learning to use HtmlDialogs. Learning is done one step at a time. Even Thomas' [HtmlDialog example](https://github.com/SketchUp/htmldialog-examples) doesn't have a fully reusable dialog until the third step, and that demonstration is aimed at existing developers with prior experience how WebDialogs work! If it was written for a wider audience I'm sure it would have at least one step without any callbacks at all, and with the current implementation such a step would require some sort of persistent reference that is never used again, which is confusing when learning.

In a wider perspective I think the difficulty to get into extension development is an increasing problem. I was lucky to start when the experience was much better, before the extensions reviews were sent from a noreply address and when the API documentation's navigation were grouped to give a better overview.

I think it is important to aim to eliminate these tresholds that could stop new users from picking up plugin development, especially given how much SU relies on plugins (the core is to a large extent a platform to run plugins in). Many developers start very casually as users trying to optimize their workflow, with no intention of becoming plugin developers, and this is something I think should be cherished.

Anyhow, to go back on topic, if the unexpected behavior can be fixed in SU (of course without causing memory leaks, break other use cases, force hard to explain choices on the API user, or confuse schooled programmers) that is good. If it is just documented that is also good.

**Comment by MSP-Greg** [comment] 2018-03-10 19:58
@Eneroth3

Re dialogs, I've given up on describing the system I need to write for dialogs, but I think it would make it very easy for beginning developers to use them.  A long time ago, I wrote a plugin, and it had several dialogs, most of which were not modal.  I started on the framework, and pushed some of it into the plugin, then stopped, then stepped away from the SU world (and into the Ruby world).  Since then, I've done some rather complex js coding, and a bunch of Ruby coding.

Like a lot of API's, the issue is that the more complex I make it, the more capabilities it has, but it also may become more difficult for beginning coders to use.  I need to think more about those kind of issues.

For now, I 'm working on a Ruby console based Minitest system, and using it right now to write tests for some of the bugs listed here...

**Comment by thomthom** [comment] 2018-03-12 13:05
> Like a lot of API's, the issue is that the more complex I make it, the more capabilities it has, but it also may become more difficult for beginning coders to use. I need to think more about those kind of issues.

So much true. SKUI was an attempt to make something that was beginner friendly - be providing an interface where you only needed to be in Ruby land - avoiding all HTML/CSS/JS. But the moment you need more complex control and widgets it quickly becomes less beginner friendly. So I stayed away from adding a ton of features to SKUI. Instead I tried to start some examples that utilized common well known web frameworks to quickly scaffold your UI. Which can scale to whatever you want. Personally I use Vue+TypeScript+Babel to compile dialogs for my own extensions. But that's not something I plan to provide an example/tutorial of any time soon.

**Comment by thomthom** [comment] 2018-08-09 16:08
Logged as SU-40221

**Closed** 2021-01-04 16:49 UTC
Labels: Ruby API, SketchUp, documentation, logged
