### ISSUE TITLE
Class: Sketchup::ComponentDefinition page does not list inherited methods

### ISSUE THREAD

**Issue by kengey** [SketchUp/api-issue-tracker#689] opened 2021-08-17 07:17 UTC
https://ruby.sketchup.com/Sketchup/ComponentDefinition.html does not list inherited methods from DrawingElement and Entity

**Comment by thomthom** [comment] 2021-08-17 08:11
hm.. we have some issues with YARD not resolving the dependencies of the files properly. We fixed some other reference that didn't show up correctly, which looks to have broken this.

**Comment by thomthom** [comment] 2021-08-17 08:13
Internal reference: SKEXT-2872

**Comment by DanRathbun** [comment] 2021-08-17 13:34
> does not list inherited methods from DrawingElement

It's actually [`Drawingelement`](https://ruby.sketchup.com/Sketchup/Drawingelement.html) but it is misspelled "DrawingElement" (as you did) in the doc strings. Since there is no such class as "DrawingElement", ... there are no inherited methods to list.

I **already** opened an issue on this ...
[Issue 652 : **ComponentDefinition is subclass of DrawingElement instead of Drawingelement**](https://github.com/SketchUp/api-issue-tracker/issues/652)

**Comment by thomthom** [comment] 2021-08-17 13:58
The issue isn't spelling. The issue is YARD not resolving file dependencies well for C source. `DrawingElement` is the defaulted value it uses when it failed to resolve the full class. (Extracted from a variable name)

**Comment by DanRathbun** [comment] 2021-08-17 14:34
Noted ... which issue do you want to cover this problem? Close one keep, the other.

**Closed** 2022-01-26 13:34 UTC
Labels: Ruby API, SketchUp, documentation
