### ISSUE TITLE
PDF images not supported in Instructor on Mac OSX

### ISSUE THREAD

**Issue by Fredosixx** [SketchUp/api-issue-tracker#476] opened 2020-05-23 13:06 UTC
**On Mac OSX**, PDF images DO NOT display in the Instructor. Images HAVE TO be PNG.

**on Windows**, both SVG and PNG images display correctly.

This is another difference between Windows and Mac.

**Comment by DanRathbun** [comment] 2020-05-23 18:57
I would have not thought this would be the case. I am under the impression that the Instructor uses the embedded Chromium framework on both platforms.

You report doesn't say anything about whether PDFs display on Windows ?

**Comment by Fredosixx** [comment] 2020-05-23 19:32
> You report doesn't say anything about whether PDFs display on Windows ?

On Windows, you must use SVG, not PDF. And on Mac, SVG are not supported, but PDF.

What I said is that SVG are well supported in the Instructors on Windows.

PNG are supported on both Mac and Windows.

**Comment by Eneroth3** [comment] 2020-05-24 08:03
Have you tried SVGs in the instructor on Mac? SVG is a very widely supported format on the web by now, and I don't think SketchUp's inability to use it on commands in the UI on Mac should prevent the instructor from using them.

Also make sure to include the correct doctype to prevent the browser from running in nay quirks mode.

**Comment by Fredosixx** [comment] 2020-05-24 11:42
In the meantime, I made further test this morning and YES, SVG are supported in the Instructor on Mac.

This means that SVG will probably be OK with HTML::Dialogs.

So PDF seems to be only required for toolbar and cursors on Mac.

**Comment by thomthom** [comment] 2020-05-25 15:40
> On Mac OSX, PDF images DO NOT display in the Instructor. Images HAVE TO be PNG.
> 
> on Windows, both SVG and PNG images display correctly.
> 
> This is another difference between Windows and Mac.

This is because the instructor is a CEF (Chromium) window. There isn't anything we can do about that.

As for the SVG vs PDF for vector icons/cursors on macOS/Windows - that is an issue that's been bothering me for a long while. We've been talking about it recently and we'll most likely end up standardizing around SVG for both platforms.

**Comment by thomthom** [comment] 2020-05-25 15:41
I'm closing this as not a bug.

**Closed by thomthom** 2020-05-25 15:41 UTC
